create table "user"
(
    id          bigint primary key generated by default as identity,
    username    varchar(100) unique not null,
    password    varchar(100)        not null,
    first_name  varchar(100)        not null,
    second_name varchar(100),
    birthdate   date,
    biography   varchar(255),
    city        varchar(100)
);
