server:
  port: 8081

spring:
  application:
    name: SocialNetwork

  liquibase:
    change-log: db/liquibase/changelog.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
